[WIP] Simulate climber
Galaxia5987/robot-2022 pull request #23
Opened 2022-01-20 17:26 UTC by adamv17

2022-01-21 13:14 UTC, barel13 requested changes

2022-01-21 13:14 UTC, barel13 commented on src/main/java/frc/robot/Constants.java
> +
You can remove the import statement

2022-01-21 13:14 UTC, barel13 commented on src/main/java/frc/robot/Ports.java
> +        public static final int ENCODER_B_CHANNEL = 1;
Please add comment that you only use this Constants for simulation

2022-01-21 13:14 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    private final PIDController m_controller = new PIDController(1.5, 0, 0);
Add the coefficients to Constants

2022-01-21 13:14 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +                    Units.degreesToRadians(255),
Constants

2022-01-21 13:14 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +
So add units!!

2022-01-21 13:14 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/commands/JoystickClimb.java
> +import frc.robot.Robot;
Remove unused import

2022-01-24 08:38 UTC, barel13 requested changes

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/Constants.java
> +        public static final double STOP_CLIMBER = 249.5; // [s]
I think it's too long (it's 4 minutes)

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/Constants.java
> +
Add units

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/commands/JoystickClimb.java
> +        if (isReady) {
You can delete the if statement

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +
You can delete this function

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    private final Solenoid stopper = new Solenoid(PneumaticsModuleType.CTREPCM, Ports.Climber.STOPPER);
Use main/follower,aux...

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +            rightMotor.set(ControlMode.Velocity, tick100ms);
You can inline it

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +        return unitModel.toVelocity(leftMotor.getSelectedSensorVelocity());
right is the main motor

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +     * @return get motors position. [ticks/rad}
[ticks/rad]

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    public void toggle() {
maybe toggleStopper?

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +        }
You can simplify this if statement

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
>          /*
config cruise velocity and max acceleration

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/Constants.java
> +        public static final double MIN_ACCELERATION = 0;
should be cruise velocity

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/Leds.java
> +package frc.robot;
The class should be in its own branch

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/Ports.java
> +        public static final int JOYSTICK_PORT = 0;
You've already defined the port in Controls

2022-01-24 08:38 UTC, barel13 commented on src/main/java/frc/robot/RobotContainer.java
>      private final Climber climber = Climber.getInstance();
You don't use this part, delete it

2022-01-24 16:07 UTC, barel13 commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +        mainMotor.setSensorPhase(Ports.Climber.MAIN_SENSOR_PHASE);
I only found out today, but you don't need to set the sensor phase of Falcons ([reference](https://phoenix-documentation.readthedocs.io/en/latest/ch14_MCSensor.html#sensor-phase)).
Also, I recommend using `TalonFXInvertType`  for the `setInverted` as it's more descriptive (I only found out about it today)

2022-01-25 15:46 UTC, barel13 approved these changes

2022-01-25 15:50 UTC, adamv17 commented
I approve

2022-01-25 15:54 UTC, merged