Simulate shooter
Galaxia5987/robot-2022 pull request #33
Opened 2022-01-21 09:48 UTC by littlebro123

Leave a comment

2022-01-24 08:46 UTC, barel13 requested changes

2022-01-24 08:46 UTC, barel13 commented on src/main/java/frc/robot/command_groups/Shoot.java
> +}
You don't need this command for the simulation, delete it

2022-01-24 08:46 UTC, barel13 commented on src/main/java/frc/robot/subsystems/shooter/commands/FeedToShooter.java
> +}
Still not related to the simulation. delete

2022-01-24 08:56 UTC, adamv17 approved these changes

2022-01-24 13:17 UTC, barel13 approved these changes

2022-01-24 15:46 UTC, katzuv commented
You shouldn't add the shooter code here, only simulation. `simulate-shooter` should be forked off `shooter`, not `main`, otherwise `shooter` has no purpose...

2022-01-25 23:02 UTC, katzuv commented
Please change the base of this branch to `shooter` (can be done by editing the PR), then I'll review it.

2022-01-26 10:46 UTC, barel13 commented on src/main/java/frc/robot/subsystems/shooter/Shooter.java
> +            simCollection.setIntegratedSensorVelocity(unitModel.toTicks100ms(Utils.secondsToMinutes(flywheelSim.getAngularVelocityRPM())));
I think you use the wrong conversion (`secindsToMinutes`)

2022-01-28 08:30 UTC, merged