Hood bits
Galaxia5987/robot-2022 pull request #81
Opened 2022-02-07 17:41 UTC by littlebro123

This includes just moving the hood back and forth until it fricking dies.

2022-02-07 18:46 UTC, adamv17 requested changes

2022-02-07 18:46 UTC, adamv17 commented on src/main/java/frc/robot/subsystems/hood/commands/bits/CheckHoodPressure.java
> +            hood.toggle();
Add some helpful prints and maybe like the intake number of runs

2022-02-07 19:04 UTC, barel13 requested changes

2022-02-07 19:04 UTC, barel13 commented on src/main/java/frc/robot/Constants.java
> +        public static final double HOOD_PRESSURE_BIT_DELTA_TIME = 0.1;
units

2022-02-07 19:04 UTC, barel13 commented on src/main/java/frc/robot/subsystems/hood/Hood.java
> +    public void toggle() {
I'm sorry, documentation

2022-02-07 19:04 UTC, barel13 commented on src/main/java/frc/robot/subsystems/hood/commands/bits/CheckHoodPressure.java
> +        this.hood = hood;
`addRequirements`

2022-02-07 20:14 UTC, adamv17 approved these changes

2022-02-08 06:48 UTC, barel13 approved these changes

2022-02-08 13:07 UTC, merged