Feature/conveyor bits
Galaxia5987/robot-2022 pull request #84
Opened 2022-02-08 15:08 UTC by littlebro123

This pull request includes a test of the color sensor (loop period and accuracy).

2022-02-09 08:37 UTC, littlebro123 commented on src/main/java/frc/robot/subsystems/conveyor/commands/bits/PostFlapTest.java
> +        conveyor.setPower(0.5);
Maybe use the `DEFAULT_POWER` constant for the conveyor

2022-02-09 08:37 UTC, littlebro123 commented on src/main/java/frc/robot/subsystems/conveyor/commands/bits/PostFlapTest.java
> +        if (wasConnected && !isConnected){
I think it's better to check the ball after it passes through the post flap beam, because that's how the logic works in the Conveyor subsystem class.

2022-02-10 12:27 UTC, barel13 requested changes

2022-02-10 12:27 UTC, barel13 commented on src/main/java/frc/robot/subsystems/conveyor/commands/bits/CheckColorSensor.java
> +        double currentDirection = -direction.getAsDouble();
why there is a minus, and why is it double?

2022-02-10 15:58 UTC, katzuv requested changes

2022-02-10 15:58 UTC, katzuv commented on src/main/java/frc/robot/subsystems/conveyor/commands/bits/CheckColorSensor.java
> +        }
I'm not sure I understand what this does, could you please explain?

2022-02-10 15:58 UTC, katzuv commented on src/main/java/frc/robot/subsystems/conveyor/commands/bits/PostFlapTest.java
> +        System.out.println("delta:" + " " + (expected - actual));
```suggestion
        System.out.println("actual: "  + actual);
        System.out.println("expected: " + expected);
        System.out.println("delta: " + (expected - actual));
```

2022-02-10 15:58 UTC, katzuv commented on src/main/java/frc/robot/subsystems/conveyor/commands/bits/PostFlapTest.java
> +    private int actual;
These members names aren't very descriptive.

2022-02-10 16:11 UTC, barel13 approved these changes

2022-02-10 16:13 UTC, adamv17 approved these changes

2022-02-10 16:14 UTC, merged