[WIP] Feature/command groups bits
Galaxia5987/robot-2022 pull request #86
Opened 2022-02-08 18:33 UTC by littlebro123

2022-02-08 18:52 UTC, barel13 requested changes

2022-02-08 18:52 UTC, barel13 commented on src/main/java/frc/robot/commandgroups/bits/TestBallFlow.java
> +        if (pickUpCargo.isScheduled()) {
I think you need to call `super.execute()` in order to call the functions from the command group

2022-02-08 18:52 UTC, barel13 commented on src/main/java/frc/robot/subsystems/conveyor/Conveyor.java
> +    public double getPower() {
docs

2022-02-08 18:52 UTC, barel13 commented on src/main/java/frc/robot/subsystems/intake/Intake.java
> +    public double getPower() {
You know what I'm gonna write...

2022-02-08 18:53 UTC, barel13 requested changes

2022-02-08 18:53 UTC, barel13 commented on src/main/java/frc/robot/commandgroups/bits/TestBallFlow.java
> +                        ShootCargo shootCargo, BooleanSupplier shootCargoIsFinished) {
You don't need to pass commands, just their parameters, and then create them internally

2022-02-09 08:06 UTC, barel13 approved these changes

2022-02-10 12:22 UTC, adamv17 approved these changes

2022-02-10 12:23 UTC, merged